### PR TITLE
Fix grammar/punctuation in phpdoc annotations

### PR DESCRIPTION
**Pull request by chalasr**

### CODE REVIEW

**Comment by michaelcullum** [comment]
:+1:

**Comment by Crell** [comment]
Actually the grammar of that comment is totally wrong anyway.  It should be "The key to delete."  Can you update the PR?

**Comment by chalasr** [comment]
@Crell Updated

**Comment by michaelcullum** [comment]
This needs mirror'ing over to php-fig/fig-standards. PR created by Crell.

**Comment by michaelcullum** [comment]
Thanks @chalasr

**Pull request merged**
