### PR TITLE
Add extends \Throwable interface to CacheException 

### PR DESCRIPTION
**Pull request by loperd**
I suggest updating CacheException and expanding it using the Throwable interface.

### CODE REVIEW

**Comment by olvlvl** [comment]
I'd like this one too but we'll have to bump minimum PHP requirements to 7.0.

**Comment by renay** [comment]
May be make extended Cache Exception of Exception class?

**Comment by jaikdean** [comment]
> I'd like this one too but we'll have to bump minimum PHP requirements to 7.0.

PHP <7.1 is EOL now, I don't see a reason to not bump this version requirement.

**Comment by Jean85** [comment]
> PHP <7.1 is EOL now, I don't see a reason to not bump this version requirement.

That would be a BC, we cannot alter a PSR like that. We started a conversation about this topic: https://groups.google.com/d/topic/php-fig/OyC3plRYhqg/discussion

**Comment by jaikdean** [comment]
I don't have access to view that, unfortunately. Is it possible to summarise the reason(s) here?

I came to this issue as we've had to create a stub class that extends `\Throwable` to appease our static analysis checks, which are raising valid alerts about throwing unthrowable interfaces. I see this being a growing concern given their increasingly widespread use.

**Comment by Jean85** [comment]
@jaikdean I may have fixed the permissions on that group, it's supposed to be public. Can you see that now?

**Comment by jaikdean** [comment]
@Jean85 Thanks, I can see that now. It's an interesting discussion with no obvious easy route to take. I'll be watching things to see how they progress; I think it'll be key to the continued success of PSRs as adoption of strict typing grows.

**Review by fizzka — APPROVED** [review]

**Comment by Jean85** [comment]
Sure. We are drafting something new right now, I hope to be able to publish it in the next few days. I'll cross-ling that in all the issues like this one.

**Comment by fizzka** [comment]
w8!!!

**Comment by Jean85** [comment]
We published the blog post, please read and provide your feedback!

https://www.php-fig.org/blog/2019/10/upgrading-psr-interfaces/

**Comment by greg0ire** [comment]
To be clear, where is the BC-break here?

I think that would be a BC-break for classes not implementing `\Throwable` already, and not marked as abstract, but that's it…

**Comment by Jean85** [comment]
This package is marked as `php: >=5.3.0`, so we would have to at least bump that.

I've drafted a PR to address these kind of issues inside the PHP-FIG: https://github.com/php-fig/fig-standards/pull/1195

**Comment by VincentLanglet** [comment]
> This package is marked as `php: >=5.3.0`, so we would have to at least bump that.
> 
> I've drafted a PR to address these kind of issues inside the PHP-FIG: [php-fig/fig-standards#1195](https://github.com/php-fig/fig-standards/pull/1195)

Hi !

I believe that bumping the php version is not a BC-break. 
Composer will resolve the right version to use according to the developer php-version. 

If you use php >7, composer will load the version 1.1.
If you use php <7, composer will load the version 1.0.1.

Moreover, https://github.com/php-fig/fig-standards/pull/1195 was merged last year, so could we update the status of this PR now ? :)

**Comment by Nyholm** [comment]
I agree with the idea but this is the wrong method. 

Please see https://github.com/php-fig/cache/pull/22

**Comment by Crell** [comment]
Please close in favor of #23.

**Pull request closed without merging**
