### PR TITLE
Be clear that the key array must be an array of strings

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by cryptiklemur** [comment]
Integers are valid too, aren't they?

**Comment by GrahamCampbell** [comment]
No. The other functions where a key is say only strings are allowed.

**Comment by cryptiklemur** [comment]
That seems like an oversight on the other methods then

Aaron Scherer

On Tue, Aug 2, 2016 at 12:57 PM -0700, "Graham Campbell" notifications@github.com wrote:

No. The other functions where a key is say only strings are allowed.

**Comment by michaelcullum** [comment]
Keys must be strings: 
- https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php#L33-L36
- https://github.com/php-fig/cache/blob/master/src/CacheItemPoolInterface.php#L23
- https://github.com/php-fig/cache/blob/master/src/CacheItemPoolInterface.php#L60
- https://github.com/php-fig/cache/blob/master/src/CacheItemPoolInterface.php#L83

So I'd say this is a good change. I also wouldn't say it's at all breaking because we already define keys must be strings in those other method signatures, and it's still an array, it's just a clarification that it's an array of strings (and therefore you're not changing the method signature, just the docblock). @php-fig/psr-6: Thoughts?

**Comment by Crell** [comment]
I agree this is a non-breaking clarification.  I don't know if we're planning to release another tagged version at any point, though (the issue's never come up before), so would this even matter?

And should we also tweak the spec itself at the same time?  That's touchy...

**Comment by michaelcullum** [comment]
I'd say yes, we apply the fix to the spec simultaneously, then just tag 1.0.1.

**Comment by michaelcullum** [comment]
Thanks

**Pull request merged**
