### PR TITLE
Add a missing asterisk in phpdoc

### PR DESCRIPTION
**Pull request by jfcherng**
as title.

### CODE REVIEW

**Comment by chalasr** [comment]
👍

**Review by garex — APPROVED** [review]
It's ok ))

**Comment by dragoonis** [comment]
Approved. 👍

**Review by michaelcullum — APPROVED** [review]

**Comment by michaelcullum** [comment]
@Crell Please 👍 this and I'll copy it across, merge it and tag.

**Comment by Crell** [comment]
Oopsies.  Good catch.

**Pull request merged**
